version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "rodosaborio"
    assignees:
      - "rodosaborio"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "rodosaborio"
    assignees:
      - "rodosaborio"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "automated"