name: Bug Report
description: Report a bug or issue with Second Opinion
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what went wrong...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command `uv run second-opinion ...`
        2. Set configuration to ...
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: What actually happened? Include any error messages.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Information about your environment
      placeholder: |
        - OS: [e.g., macOS 14.0, Ubuntu 22.04, Windows 11]
        - Python version: [e.g., 3.12.0]
        - Second Opinion version: [e.g., 0.1.0]
        - uv version: [e.g., 0.4.0]
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information like API keys)
      placeholder: |
        Environment variables, config files, command line arguments used
        (Remember to remove any API keys or sensitive information!)
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any relevant error messages or logs
      placeholder: |
        Include full error tracebacks, log output, etc.
        (Remember to remove any API keys or sensitive information!)
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to make sure this is not a duplicate
          required: true
        - label: I have removed all sensitive information (API keys, etc.) from this report
          required: true
        - label: I have included all the requested information above
          required: true